
// vaConstants.js
// Auto-generated constants for VA Calculator

// 2025 VA Disability Compensation Rates (Veteran alone)
const payRatesBase = {
  10:   175.51,
  20:   346.95,
  30:   537.42,
  40:   774.16,
  50:  1102.04,
  60:  1395.93,
  70:  1759.19,
  80:  2044.89,
  90:  2297.96,
  100: 3831.30
};

// Grouped VA diagnostic codes, conditions, DBQs, and icons
const groupedConditionCodes = {
  1100: { condition: "6518  Laryngectomy, total.", dbq: "Unknown", icon: "" },
  1968: { condition: "Ratings for Pulmonary Tuberculosis Entitled on August 19,", dbq: "Unknown", icon: "" },
  5000: { condition: "Osteomyelitis", dbq: "Unknown", icon: "" },
  5001: { condition: "Bones and joints", dbq: "Unknown", icon: "" },
  5002: { condition: "Rheumatoid (atrophic)", dbq: "Unknown", icon: "" },
  5003: { condition: "Degenerative (hypertrophic or osteoarthritis)", dbq: "Joint Conditions", icon: "🦾" },
  5004: { condition: "Gonorrheal", dbq: "Unknown", icon: "" },
  5005: { condition: "Pneumococcic", dbq: "Unknown", icon: "" },
  5006: { condition: "Typhoid", dbq: "Unknown", icon: "" },
  5007: { condition: "Syphilitic", dbq: "Unknown", icon: "" },
  5008: { condition: "Streptococcic", dbq: "Unknown", icon: "" },
  5009: { condition: "Other types", dbq: "Unknown", icon: "" },
  5010: { condition: "Due to trauma", dbq: "Joint Conditions", icon: "🦾" },
  5011: { condition: "Caisson disease", dbq: "Unknown", icon: "" },
  5012: { condition: "Bones", dbq: "Unknown", icon: "" },
  5013: { condition: "Osteoporosis, with joint manifestations", dbq: "Unknown", icon: "" },
  5014: { condition: "Osteomalacia", dbq: "Unknown", icon: "" },
  5015: { condition: "Bones", dbq: "Unknown", icon: "" },
  5016: { condition: "Osteitis deformans", dbq: "Unknown", icon: "" },
  5017: { condition: "Gout", dbq: "Unknown", icon: "" },
  5018: { condition: "Hydrarthrosis, intermittent", dbq: "Unknown", icon: "" },
  5019: { condition: "Bursitis", dbq: "Unknown", icon: "" },
  5020: { condition: "Synovitis", dbq: "Unknown", icon: "" },
  5021: { condition: "Myositis", dbq: "Unknown", icon: "" },
  5022: { condition: "Periostitis", dbq: "Unknown", icon: "" },
  5023: { condition: "Myositis ossificans", dbq: "Unknown", icon: "" },
  5024: { condition: "Tenosynovitis", dbq: "Unknown", icon: "" },
  5025: { condition: "Fibromyalgia", dbq: "Unknown", icon: "" },
  5051: { condition: "Shoulder replacement", dbq: "Unknown", icon: "" },
  5052: { condition: "Elbow replacement", dbq: "Unknown", icon: "" },
  5053: { condition: "Wrist replacement", dbq: "Unknown", icon: "" },
  5054: { condition: "Hip replacement", dbq: "Unknown", icon: "" },
  5055: { condition: "Knee replacement", dbq: "Unknown", icon: "" },
  5056: { condition: "Ankle replacement", dbq: "Unknown", icon: "" },
  5104: { condition: "One hand and loss of use of one foot", dbq: "Unknown", icon: "" },
  5105: { condition: "One foot and loss of use of one hand", dbq: "Unknown", icon: "" },
  5106: { condition: "Both hands", dbq: "Unknown", icon: "" },
  5107: { condition: "Both feet", dbq: "Unknown", icon: "" },
  5108: { condition: "One hand and one foot", dbq: "Unknown", icon: "" },
  5109: { condition: "Both hands", dbq: "Unknown", icon: "" },
  5110: { condition: "Both feet", dbq: "Unknown", icon: "" },
  5111: { condition: "One hand and one foot", dbq: "Unknown", icon: "" },
  5120: { condition: "Disarticulation", dbq: "Unknown", icon: "" },
  5121: { condition: "Above insertion of deltoid", dbq: "Unknown", icon: "" },
  5122: { condition: "Below insertion of deltoid", dbq: "Unknown", icon: "" },
  5123: { condition: "Above insertion of pronator teres", dbq: "Unknown", icon: "" },
  5124: { condition: "Below insertion of pronator teres", dbq: "Unknown", icon: "" },
  5125: { condition: "Hand", dbq: "Unknown", icon: "" },
  5126: { condition: "Digits, five of one hand", dbq: "Unknown", icon: "" },
  5127: { condition: "Thumb, index, long and ring", dbq: "Unknown", icon: "" },
  5128: { condition: "Thumb, index, long and little", dbq: "Unknown", icon: "" },
  5129: { condition: "Thumb, index, ring and little", dbq: "Unknown", icon: "" },
  5130: { condition: "Thumb, long, ring and little", dbq: "Unknown", icon: "" },
  5131: { condition: "Index, long, ring and little", dbq: "Unknown", icon: "" },
  5132: { condition: "Thumb, index and long", dbq: "Unknown", icon: "" },
  5133: { condition: "Thumb, index and ring", dbq: "Unknown", icon: "" },
  5134: { condition: "Thumb, index and little", dbq: "Unknown", icon: "" },
  5135: { condition: "Thumb, long and ring", dbq: "Unknown", icon: "" },
  5136: { condition: "Thumb, long and little", dbq: "Unknown", icon: "" },
  5137: { condition: "Thumb, ring and little", dbq: "Unknown", icon: "" },
  5138: { condition: "Index, long and ring", dbq: "Unknown", icon: "" },
  5139: { condition: "Index, long and little", dbq: "Unknown", icon: "" },
  5140: { condition: "Index, ring and little", dbq: "Unknown", icon: "" },
  5141: { condition: "Long, ring and little", dbq: "Unknown", icon: "" },
  5142: { condition: "Thumb and index", dbq: "Unknown", icon: "" },
  5143: { condition: "Thumb and long", dbq: "Unknown", icon: "" },
  5144: { condition: "Thumb and ring", dbq: "Unknown", icon: "" },
  5145: { condition: "Thumb and little", dbq: "Unknown", icon: "" },
  5146: { condition: "Index and long", dbq: "Unknown", icon: "" },
  5147: { condition: "Index and ring", dbq: "Unknown", icon: "" },
  5148: { condition: "Index and little", dbq: "Unknown", icon: "" },
  5149: { condition: "Long and ring", dbq: "Unknown", icon: "" },
  5150: { condition: "Long and little", dbq: "Unknown", icon: "" },
  5151: { condition: "Ring and little", dbq: "Unknown", icon: "" },
  5152: { condition: "Thumb", dbq: "Unknown", icon: "" },
  5153: { condition: "Index finger", dbq: "Unknown", icon: "" },
  5154: { condition: "Long finger", dbq: "Unknown", icon: "" },
  5155: { condition: "Ring finger", dbq: "Unknown", icon: "" },
  5156: { condition: "Little finger", dbq: "Unknown", icon: "" },
  5160: { condition: "Disarticulation", dbq: "Unknown", icon: "" },
  5161: { condition: "Upper third", dbq: "Unknown", icon: "" },
  5162: { condition: "Middle or lower thirds", dbq: "Unknown", icon: "" },
  5163: { condition: "With defective stump", dbq: "Unknown", icon: "" },
  5164: { condition: "Not improvable by prosthesis controlled by natural knee action", dbq: "Unknown", icon: "" },
  5165: { condition: "At a lower level, permitting prosthesis", dbq: "Unknown", icon: "" },
  5166: { condition: "Forefoot, proximal to metatarsal bones", dbq: "Unknown", icon: "" },
  5167: { condition: "Foot", dbq: "Unknown", icon: "" },
  5170: { condition: "Toes, all, without metatarsal loss", dbq: "Unknown", icon: "" },
  5171: { condition: "Toe, great", dbq: "Unknown", icon: "" },
  5172: { condition: "Toes, other than great, with removal of metatarsal head", dbq: "Unknown", icon: "" },
  5173: { condition: "Toes, three or more, without metatarsal involvement", dbq: "Unknown", icon: "" },
  5200: { condition: "Scapulohumeral articulation", dbq: "Unknown", icon: "" },
  5201: { condition: "Arm", dbq: "Unknown", icon: "" },
  5202: { condition: "Humerus", dbq: "Unknown", icon: "" },
  5203: { condition: "Clavicle or scapula", dbq: "Unknown", icon: "" },
  5205: { condition: "Elbow", dbq: "Unknown", icon: "" },
  5206: { condition: "Forearm", dbq: "Unknown", icon: "" },
  5207: { condition: "Forearm", dbq: "Unknown", icon: "" },
  5208: { condition: "Forearm", dbq: "Unknown", icon: "" },
  5209: { condition: "Elbow", dbq: "Unknown", icon: "" },
  5210: { condition: "Radius and ulna", dbq: "Unknown", icon: "" },
  5211: { condition: "Ulna", dbq: "Unknown", icon: "" },
  5212: { condition: "Radius", dbq: "Unknown", icon: "" },
  5213: { condition: "Supination and pronation", dbq: "Unknown", icon: "" },
  5214: { condition: "Wrist", dbq: "Unknown", icon: "" },
  5215: { condition: "Wrist, limitation of motion", dbq: "Unknown", icon: "" },
  5216: { condition: "Five digits of one hand", dbq: "Unknown", icon: "" },
  5217: { condition: "Four digits of one hand", dbq: "Unknown", icon: "" },
  5218: { condition: "Three digits of one hand", dbq: "Unknown", icon: "" },
  5219: { condition: "Two digits of one hand", dbq: "Unknown", icon: "" },
  5220: { condition: "Five digits of one hand", dbq: "Unknown", icon: "" },
  5221: { condition: "Four digits of one hand", dbq: "Unknown", icon: "" },
  5222: { condition: "Three digits of one hand", dbq: "Unknown", icon: "" },
  5223: { condition: "Two digits of one hand", dbq: "Unknown", icon: "" },
  5224: { condition: "Thumb", dbq: "Unknown", icon: "" },
  5225: { condition: "Index finger", dbq: "Unknown", icon: "" },
  5226: { condition: "Long finger", dbq: "Unknown", icon: "" },
  5227: { condition: "Ring or little finger", dbq: "Unknown", icon: "" },
  5228: { condition: "Thumb", dbq: "Unknown", icon: "" },
  5229: { condition: "Index or long finger", dbq: "Unknown", icon: "" },
  5230: { condition: "Ring or little finger", dbq: "Unknown", icon: "" },
  5235: { condition: "Vertebral fracture or dislocation", dbq: "Unknown", icon: "" },
  5236: { condition: "Sacroiliac", dbq: "Unknown", icon: "" },
  5237: { condition: "Cervical strain", dbq: "Cervical Spine (Neck) Conditions", icon: "🔗" },
  5238: { condition: "Spinal stenosis", dbq: "Lumbosacral and Thoracic Spine Conditions", icon: "🦴" },
  5239: { condition: "Spondylolisthesis or segmental instability, spine", dbq: "Lumbosacral and Thoracic Spine Conditions", icon: "🦴" },
  5240: { condition: "Ankylosing spondylitis", dbq: "Unknown", icon: "" },
  5241: { condition: "Spinal fusion", dbq: "Unknown", icon: "" },
  5242: { condition: "Degenerative arthritis", dbq: "Lumbosacral and Thoracic Spine Conditions", icon: "🦴" },
  5243: { condition: "Intervertebral disc syndrome", dbq: "Unknown", icon: "" },
  5250: { condition: "Hip", dbq: "Unknown", icon: "" },
  5251: { condition: "Thigh", dbq: "Unknown", icon: "" },
  5252: { condition: "Thigh", dbq: "Unknown", icon: "" },
  5253: { condition: "Thigh", dbq: "Unknown", icon: "" },
  5254: { condition: "Flail joint", dbq: "Unknown", icon: "" },
  5255: { condition: "Femur", dbq: "Unknown", icon: "" },
  5256: { condition: "Knee", dbq: "Cervical Spine (Neck) Conditions", icon: "🔗" },
  5257: { condition: "Knee, other", dbq: "Knee and Lower Leg Conditions", icon: "🦵" },
  5258: { condition: "Cartilage, semilunar", dbq: "Knee and Lower Leg Conditions", icon: "🦵" },
  5259: { condition: "Cartilage, semilunar", dbq: "Unknown", icon: "" },
  5260: { condition: "Leg", dbq: "Unknown", icon: "" },
  5261: { condition: "Leg", dbq: "Unknown", icon: "" },
  5262: { condition: "Tibia and fibula", dbq: "Unknown", icon: "" },
  5263: { condition: "Genu recurvatum", dbq: "Unknown", icon: "" },
  5270: { condition: "Ankle", dbq: "Unknown", icon: "" },
  5271: { condition: "Ankle", dbq: "Foot Conditions", icon: "🦶" },
  5272: { condition: "Subastragalar or tarsal joint", dbq: "Unknown", icon: "" },
  5273: { condition: "Os calcis or astragalus", dbq: "Unknown", icon: "" },
  5274: { condition: "Astragalectomy", dbq: "Unknown", icon: "" },
  5275: { condition: "Shortening of the lower extremity", dbq: "Unknown", icon: "" },
  5276: { condition: "Flatfoot, acquired", dbq: "Foot Conditions", icon: "🦶" },
  5277: { condition: "Weak foot", dbq: "Unknown", icon: "" },
  5278: { condition: "Pes cavus (Claw foot) acquired", dbq: "Unknown", icon: "" },
  5279: { condition: "Morton's", dbq: "Unknown", icon: "" },
  5280: { condition: "Valgus", dbq: "Unknown", icon: "" },
  5281: { condition: "Rigidus", dbq: "Unknown", icon: "" },
  5282: { condition: "Hammer toe", dbq: "Unknown", icon: "" },
  5283: { condition: "Tarsal or metatarsal bones", dbq: "Unknown", icon: "" },
  5284: { condition: "Foot", dbq: "Foot Conditions", icon: "🦶" },
  5296: { condition: "Skull, part of", dbq: "Unknown", icon: "" },
  5297: { condition: "Ribs", dbq: "Unknown", icon: "" },
  5298: { condition: "Coccyx", dbq: "Unknown", icon: "" },
  5301: { condition: "Group I Function: Upward rotation of scapula", dbq: "Unknown", icon: "" },
  5302: { condition: "Group II Function: Depression of arm", dbq: "Unknown", icon: "" },
  5303: { condition: "Group III Function: Elevation and abduction of arm", dbq: "Unknown", icon: "" },
  5304: { condition: "Group IV Function: Stabilization of shoulder", dbq: "Unknown", icon: "" },
  5305: { condition: "Group V Function: Elbow supination", dbq: "Unknown", icon: "" },
  5306: { condition: "Group VI Function: Extension of elbow", dbq: "Unknown", icon: "" },
  5307: { condition: "Group VII Function: Flexion of wrist and fingers", dbq: "Unknown", icon: "" },
  5308: { condition: "Group VIII Function: Extension of wrist, fingers, thumb", dbq: "Unknown", icon: "" },
  5309: { condition: "Group IX Function: Forearm muscles", dbq: "Unknown", icon: "" },
  5310: { condition: "Group X Function: Movement of forefoot and toes", dbq: "Unknown", icon: "" },
  5311: { condition: "Group XI Function: Propulsion of foot", dbq: "Unknown", icon: "" },
  5312: { condition: "Group XII Function: Dorsiflexion", dbq: "Unknown", icon: "" },
  5313: { condition: "Group XIII Function: Extension of hip and flexion of knee", dbq: "Unknown", icon: "" },
  5314: { condition: "Group XIV Function: Extension of knee", dbq: "Unknown", icon: "" },
  5315: { condition: "Group XV Function: Adduction of hip", dbq: "Unknown", icon: "" },
  5316: { condition: "Group XVI Function: Flexion of hip", dbq: "Unknown", icon: "" },
  5317: { condition: "Group XVII Function: Extension of hip", dbq: "Unknown", icon: "" },
  5318: { condition: "Group XVIII Function: Outward rotation of thigh", dbq: "Unknown", icon: "" },
  5319: { condition: "Group XIX Function: Abdominal wall and lower thorax", dbq: "Unknown", icon: "" },
  5320: { condition: "Group XX Function: Postural support of body", dbq: "Unknown", icon: "" },
  5321: { condition: "Group XXI Function: Respiration", dbq: "Unknown", icon: "" },
  5322: { condition: "Group XXII Function: Rotary and forward movements, head", dbq: "Unknown", icon: "" },
  5323: { condition: "Group XXIII Function: Movements of head", dbq: "Unknown", icon: "" },
  5324: { condition: "Rupture", dbq: "Unknown", icon: "" },
  5325: { condition: "Facial", dbq: "Unknown", icon: "" },
  5326: { condition: "Muscle", dbq: "Unknown", icon: "" },
  5327: { condition: "Muscle", dbq: "Unknown", icon: "" },
  5328: { condition: "Muscle", dbq: "Unknown", icon: "" },
  5329: { condition: "Muscle, fat, or fibrous connected", dbq: "Unknown", icon: "" },
  6000: { condition: "Uveitis", dbq: "Unknown", icon: "" },
  6001: { condition: "Keratitis", dbq: "Unknown", icon: "" },
  6003: { condition: "Iritis", dbq: "Unknown", icon: "" },
  6004: { condition: "Cyclitis", dbq: "Unknown", icon: "" },
  6005: { condition: "Choroiditis", dbq: "Unknown", icon: "" },
  6006: { condition: "Retinitis", dbq: "Unknown", icon: "" },
  6007: { condition: "Intra-ocular", dbq: "Unknown", icon: "" },
  6008: { condition: "Retina detachment of", dbq: "Unknown", icon: "" },
  6009: { condition: "Eye, unhealed", dbq: "Unknown", icon: "" },
  6010: { condition: "Eye", dbq: "Unknown", icon: "" },
  6011: { condition: "Retina", dbq: "Unknown", icon: "" },
  6012: { condition: "Congestive or inflammatory", dbq: "Unknown", icon: "" },
  6013: { condition: "Simple, primary, noncongestive", dbq: "Unknown", icon: "" },
  6014: { condition: "Eyeball", dbq: "Unknown", icon: "" },
  6015: { condition: "Eyeball and adnexa", dbq: "Unknown", icon: "" },
  6016: { condition: "Nystagmus, central", dbq: "Unknown", icon: "" },
  6017: { condition: "Trachomatous", dbq: "Unknown", icon: "" },
  6018: { condition: "Other", dbq: "Unknown", icon: "" },
  6019: { condition: "Ptosis", dbq: "Unknown", icon: "" },
  6020: { condition: "Ectropion", dbq: "Unknown", icon: "" },
  6021: { condition: "Entropion", dbq: "Unknown", icon: "" },
  6022: { condition: "Lagophthalmos", dbq: "Unknown", icon: "" },
  6023: { condition: "Eyebrows", dbq: "Unknown", icon: "" },
  6024: { condition: "Eyelashes", dbq: "Unknown", icon: "" },
  6025: { condition: "Epiphora", dbq: "Unknown", icon: "" },
  6026: { condition: "Optic", dbq: "Unknown", icon: "" },
  6027: { condition: "Traumatic", dbq: "Unknown", icon: "" },
  6028: { condition: "Senile and others", dbq: "Unknown", icon: "" },
  6029: { condition: "Aphakia", dbq: "Unknown", icon: "" },
  6030: { condition: "Accommodation", dbq: "Unknown", icon: "" },
  6031: { condition: "Dacryocystitis", dbq: "Unknown", icon: "" },
  6032: { condition: "Eyelids", dbq: "Unknown", icon: "" },
  6033: { condition: "Lens, crystalline", dbq: "Unknown", icon: "" },
  6034: { condition: "Pterygium", dbq: "Unknown", icon: "" },
  6035: { condition: "Keratoconus", dbq: "Unknown", icon: "" },
  6061: { condition: "Both eyes", dbq: "Unknown", icon: "" },
  6062: { condition: "Both eyes, only light perception", dbq: "Unknown", icon: "" },
  6063: { condition: "5/200 (1.5/60)", dbq: "Unknown", icon: "" },
  6064: { condition: "10/200 (3/60); 15/200 (4.5/60); 20/200 (6/60)", dbq: "Unknown", icon: "" },
  6065: { condition: "20/100 (6/30); 20/70 (6/21); 20/50 (6/15)", dbq: "Unknown", icon: "" },
  6066: { condition: "20/40 (6/12)", dbq: "Unknown", icon: "" },
  6067: { condition: "5/200 (1.5/60)", dbq: "Unknown", icon: "" },
  6068: { condition: "10/200 (3/60); 15/200 (4.5/60); 20/200 (6/60)", dbq: "Unknown", icon: "" },
  6069: { condition: "20/100 (6/30); 20/70 (6/21); 20/50 (6/15)", dbq: "Unknown", icon: "" },
  6070: { condition: "20/40 (6/12)", dbq: "Unknown", icon: "" },
  6071: { condition: "5/200 (1.5/60)", dbq: "Unknown", icon: "" },
  6072: { condition: "10/200 (3/60); 15/200 (4.5/60); 20/200 (6/60)", dbq: "Unknown", icon: "" },
  6073: { condition: "20/100 (6/30); 20/70 (6/21); 20/50 (6/15)", dbq: "Unknown", icon: "" },
  6074: { condition: "20/40 (6/12)", dbq: "Unknown", icon: "" },
  6075: { condition: "20/200 (6/60)", dbq: "Unknown", icon: "" },
  6076: { condition: "20/100 (6/30); 20/70 (6/21); 20/50 (6/15)", dbq: "Unknown", icon: "" },
  6077: { condition: "20/40 (6/12)", dbq: "Unknown", icon: "" },
  6078: { condition: "20/50 (6/15)", dbq: "Unknown", icon: "" },
  6079: { condition: "20/40 (6/12)", dbq: "Unknown", icon: "" },
  6080: { condition: "Field vision", dbq: "Unknown", icon: "" },
  6090: { condition: "Diplopia", dbq: "Unknown", icon: "" },
  6091: { condition: "Symblepharon", dbq: "Unknown", icon: "" },
  6092: { condition: "Diplopia, limited muscle function, eye", dbq: "Unknown", icon: "" },
  6200: { condition: "Suppurative", dbq: "Hearing Loss", icon: "🦻" },
  6201: { condition: "Nonsuppurative", dbq: "Unknown", icon: "" },
  6202: { condition: "Otosclerosis", dbq: "Unknown", icon: "" },
  6204: { condition: "Peripheral vestibular disorders", dbq: "Unknown", icon: "" },
  6205: { condition: "Meniere's", dbq: "Unknown", icon: "" },
  6207: { condition: "Auricle", dbq: "Unknown", icon: "" },
  6208: { condition: "Ear", dbq: "Unknown", icon: "" },
  6209: { condition: "Ear", dbq: "Unknown", icon: "" },
  6210: { condition: "Externa", dbq: "Unknown", icon: "" },
  6211: { condition: "Tympanic membrane", dbq: "Unknown", icon: "" },
  6260: { condition: "Tinnitus, recurrent", dbq: "Audiology and Tinnitus", icon: "🎧" },
  6275: { condition: "Smell, sense of", dbq: "Unknown", icon: "" },
  6276: { condition: "Taste, sense of", dbq: "Unknown", icon: "" },
  6300: { condition: "Cholera, Asiatic", dbq: "Unknown", icon: "" },
  6301: { condition: "Visceral Leishmaniasis", dbq: "Unknown", icon: "" },
  6302: { condition: "Leprosy (Hansen's)", dbq: "Unknown", icon: "" },
  6304: { condition: "Malaria", dbq: "Unknown", icon: "" },
  6305: { condition: "Lymphatic filariasis", dbq: "Unknown", icon: "" },
  6306: { condition: "Bartonellosis", dbq: "Unknown", icon: "" },
  6307: { condition: "Plague", dbq: "Unknown", icon: "" },
  6308: { condition: "Relapsing", dbq: "Unknown", icon: "" },
  6309: { condition: "Rheumatic", dbq: "Unknown", icon: "" },
  6310: { condition: "Syphilis", dbq: "Unknown", icon: "" },
  6311: { condition: "Miliary", dbq: "Unknown", icon: "" },
  6313: { condition: "Avitaminosis", dbq: "Unknown", icon: "" },
  6314: { condition: "Beriberi", dbq: "Unknown", icon: "" },
  6315: { condition: "Pellagra", dbq: "Unknown", icon: "" },
  6316: { condition: "Brucellosis", dbq: "Unknown", icon: "" },
  6317: { condition: "Typhus, scrub", dbq: "Unknown", icon: "" },
  6318: { condition: "Melioidosis", dbq: "Unknown", icon: "" },
  6319: { condition: "Lyme", dbq: "Unknown", icon: "" },
  6320: { condition: "Parasitic", dbq: "Unknown", icon: "" },
  6350: { condition: "Erythematosus", dbq: "Unknown", icon: "" },
  6351: { condition: "HIV-Related Illness", dbq: "Unknown", icon: "" },
  6354: { condition: "Chronic Fatigue Syndrome (CFS)", dbq: "Unknown", icon: "" },
  6504: { condition: "Nose, part of, or scars", dbq: "Unknown", icon: "" },
  6510: { condition: "Pansinusitis", dbq: "Unknown", icon: "" },
  6511: { condition: "Ethmoid", dbq: "Unknown", icon: "" },
  6512: { condition: "Frontal", dbq: "Unknown", icon: "" },
  6513: { condition: "Maxillary", dbq: "Nasal and Sinus Conditions", icon: "👃" },
  6514: { condition: "Sphenoid", dbq: "Unknown", icon: "" },
  6515: { condition: "Tuberculous", dbq: "Unknown", icon: "" },
  6516: { condition: "Chronic", dbq: "Unknown", icon: "" },
  6518: { condition: "Laryngectomy", dbq: "Unknown", icon: "" },
  6519: { condition: "Aphonia, organic", dbq: "Unknown", icon: "" },
  6520: { condition: "Larynx, stenosis of", dbq: "Unknown", icon: "" },
  6521: { condition: "Pharynx", dbq: "Unknown", icon: "" },
  6522: { condition: "Allergic or vasomotor", dbq: "Nasal and Sinus Conditions", icon: "👃" },
  6523: { condition: "Bacterial", dbq: "Unknown", icon: "" },
  6524: { condition: "Granulomatous", dbq: "Unknown", icon: "" },
  6600: { condition: "Bronchitis", dbq: "Respiratory Conditions", icon: "🌬️" },
  6601: { condition: "Bronchiectasis", dbq: "Unknown", icon: "" },
  6602: { condition: "Asthma, bronchial", dbq: "Respiratory Conditions", icon: "🌬️" },
  6603: { condition: "Emphysema, pulmonary", dbq: "Unknown", icon: "" },
  6604: { condition: "Chronic obstructive pulmonary disease", dbq: "Respiratory Conditions", icon: "🌬️" },
  6701: { condition: "Active, far advanced", dbq: "Unknown", icon: "" },
  6702: { condition: "Active, moderately advanced", dbq: "Unknown", icon: "" },
  6703: { condition: "Active, minimal", dbq: "Unknown", icon: "" },
  6704: { condition: "Active, advancement unspecified", dbq: "Unknown", icon: "" },
  6721: { condition: "Inactive, far advanced", dbq: "Unknown", icon: "" },
  6722: { condition: "Inactive, moderately advanced", dbq: "Unknown", icon: "" },
  6723: { condition: "Inactive, minimal", dbq: "Unknown", icon: "" },
  6724: { condition: "Inactive, advancement unspecified", dbq: "Unknown", icon: "" },
  6730: { condition: "Active, chronic", dbq: "Unknown", icon: "" },
  6731: { condition: "Inactive, chronic", dbq: "Unknown", icon: "" },
  6732: { condition: "Pleurisy, active or inactive", dbq: "Unknown", icon: "" },
  6817: { condition: "Vascular disease", dbq: "Unknown", icon: "" },
  6819: { condition: "Respiratory", dbq: "Unknown", icon: "" },
  6820: { condition: "Respiratory", dbq: "Unknown", icon: "" },
  6822: { condition: "Actinomycosis", dbq: "Unknown", icon: "" },
  6823: { condition: "Nocardiosis", dbq: "Unknown", icon: "" },
  6824: { condition: "Lung", dbq: "Unknown", icon: "" },
  6825: { condition: "Fibrosis of lung, diffuse interstitial", dbq: "Unknown", icon: "" },
  6826: { condition: "Desquamative interstitial pneumonitis", dbq: "Unknown", icon: "" },
  6827: { condition: "Alveolar proteinosis", dbq: "Unknown", icon: "" },
  6828: { condition: "Eosinophilic granuloma of lung", dbq: "Unknown", icon: "" },
  6829: { condition: "Drug-induced", dbq: "Unknown", icon: "" },
  6830: { condition: "Radiation-induced", dbq: "Unknown", icon: "" },
  6831: { condition: "Hypersensitivity", dbq: "Unknown", icon: "" },
  6832: { condition: "Pneumoconiosis", dbq: "Unknown", icon: "" },
  6833: { condition: "Asbestosis", dbq: "Unknown", icon: "" },
  6834: { condition: "Histoplasmosis", dbq: "Unknown", icon: "" },
  6835: { condition: "Coccidioidomycosis", dbq: "Unknown", icon: "" },
  6836: { condition: "Blastomycosis", dbq: "Unknown", icon: "" },
  6837: { condition: "Cryptococcosis", dbq: "Unknown", icon: "" },
  6838: { condition: "Aspergillosis", dbq: "Unknown", icon: "" },
  6839: { condition: "Mucormycosis", dbq: "Unknown", icon: "" },
  6840: { condition: "Paralysis or paresis", dbq: "Unknown", icon: "" },
  6841: { condition: "Spinal cord", dbq: "Unknown", icon: "" },
  6842: { condition: "Kyphoscoliosis, pectus excavatum / carinatum", dbq: "Unknown", icon: "" },
  6843: { condition: "Traumatic chest wall defect", dbq: "Unknown", icon: "" },
  6844: { condition: "Post-surgical residual", dbq: "Unknown", icon: "" },
  6845: { condition: "Pleural effusion or fibrosis", dbq: "Unknown", icon: "" },
  6846: { condition: "Sarcoidosis", dbq: "Unknown", icon: "" },
  6847: { condition: "Sleep Apnea", dbq: "Sleep Apnea", icon: "😴" },
  7000: { condition: "Valvular heart disease", dbq: "Unknown", icon: "" },
  7001: { condition: "Endocarditis", dbq: "Unknown", icon: "" },
  7002: { condition: "Pericarditis", dbq: "Unknown", icon: "" },
  7003: { condition: "Pericardial adhesions", dbq: "Unknown", icon: "" },
  7004: { condition: "Syphilitic heart disease", dbq: "Unknown", icon: "" },
  7005: { condition: "Arteriosclerotic heart disease", dbq: "Coronary Artery Disease", icon: "💓" },
  7006: { condition: "Myocardial infarction", dbq: "Unknown", icon: "" },
  7007: { condition: "Heart disease", dbq: "Unknown", icon: "" },
  7008: { condition: "Hyperthyroid heart disease", dbq: "Unknown", icon: "" },
  7010: { condition: "Supraventricular", dbq: "Unknown", icon: "" },
  7011: { condition: "Ventricular", dbq: "Unknown", icon: "" },
  7015: { condition: "Atrioventricular block", dbq: "Unknown", icon: "" },
  7016: { condition: "Heart valve replacement", dbq: "Unknown", icon: "" },
  7017: { condition: "Coronary bypass surgery", dbq: "Unknown", icon: "" },
  7018: { condition: "Pacemakers, implantable", dbq: "Unknown", icon: "" },
  7019: { condition: "Transplantation", dbq: "Unknown", icon: "" },
  7020: { condition: "Cardiomyopathy", dbq: "Unknown", icon: "" },
  7101: { condition: "diagnostic code", dbq: "Hypertension", icon: "❤️" },
  7110: { condition: "Aortic", dbq: "Unknown", icon: "" },
  7111: { condition: "Large artery", dbq: "Unknown", icon: "" },
  7112: { condition: "Small artery", dbq: "Unknown", icon: "" },
  7113: { condition: "Arteriovenous fistula", dbq: "Unknown", icon: "" },
  7114: { condition: "Arteriosclerosis obliterans", dbq: "Unknown", icon: "" },
  7115: { condition: "Buerger's", dbq: "Unknown", icon: "" },
  7117: { condition: "Raynaud's", dbq: "Unknown", icon: "" },
  7118: { condition: "Angioneurotic edema", dbq: "Unknown", icon: "" },
  7119: { condition: "Erythromelalgia", dbq: "Unknown", icon: "" },
  7120: { condition: "Varicose veins", dbq: "Unknown", icon: "" },
  7121: { condition: "Post-phlebitic syndrome", dbq: "Unknown", icon: "" },
  7122: { condition: "Cold injury residuals", dbq: "Unknown", icon: "" },
  7123: { condition: "Vascular origin", dbq: "Unknown", icon: "" },
  7200: { condition: "Mouth", dbq: "Unknown", icon: "" },
  7201: { condition: "Lips", dbq: "Unknown", icon: "" },
  7202: { condition: "Tongue, loss of whole or part", dbq: "Unknown", icon: "" },
  7203: { condition: "Stricture", dbq: "Unknown", icon: "" },
  7204: { condition: "Spasm", dbq: "Unknown", icon: "" },
  7205: { condition: "Diverticulum", dbq: "Unknown", icon: "" },
  7301: { condition: "Peritoneum, adhesions", dbq: "Unknown", icon: "" },
  7304: { condition: "Gastric", dbq: "Unknown", icon: "" },
  7305: { condition: "Duodenal", dbq: "Unknown", icon: "" },
  7306: { condition: "Marginal", dbq: "Unknown", icon: "" },
  7307: { condition: "Gastritis, hypertrophic", dbq: "Unknown", icon: "" },
  7308: { condition: "Postgastrectomy syndromes", dbq: "Unknown", icon: "" },
  7309: { condition: "Stomach, stenosis of", dbq: "Unknown", icon: "" },
  7310: { condition: "Stomach, residuals of", dbq: "Unknown", icon: "" },
  7311: { condition: "Liver, residuals", dbq: "Unknown", icon: "" },
  7312: { condition: "Cirrhosis", dbq: "Unknown", icon: "" },
  7314: { condition: "Cholecystitis, chronic", dbq: "Unknown", icon: "" },
  7315: { condition: "Cholelithiasis, chronic", dbq: "Unknown", icon: "" },
  7316: { condition: "Cholangitis, chronic", dbq: "Unknown", icon: "" },
  7317: { condition: "Gall bladder", dbq: "Unknown", icon: "" },
  7318: { condition: "Gall bladder", dbq: "Unknown", icon: "" },
  7319: { condition: "Irritable colon syndrome", dbq: "Unknown", icon: "" },
  7321: { condition: "Amebiasis", dbq: "Unknown", icon: "" },
  7322: { condition: "Dysentery, bacillary", dbq: "Unknown", icon: "" },
  7323: { condition: "Colitis, ulcerative", dbq: "Unknown", icon: "" },
  7324: { condition: "Distomiasis, intestinal or hepatic", dbq: "Unknown", icon: "" },
  7325: { condition: "Enteritis, chronic", dbq: "Unknown", icon: "" },
  7326: { condition: "Enterocolitis, chronic", dbq: "Unknown", icon: "" },
  7327: { condition: "Diverticulitis", dbq: "Unknown", icon: "" },
  7328: { condition: "Small", dbq: "Unknown", icon: "" },
  7329: { condition: "Large", dbq: "Unknown", icon: "" },
  7330: { condition: "Intestine, fistula of", dbq: "Unknown", icon: "" },
  7331: { condition: "Peritonitis", dbq: "Unknown", icon: "" },
  7332: { condition: "Rectum & anus", dbq: "Unknown", icon: "" },
  7333: { condition: "Rectum & anus, stricture", dbq: "Unknown", icon: "" },
  7334: { condition: "Prolapse", dbq: "Unknown", icon: "" },
  7335: { condition: "Fistula in ano", dbq: "Unknown", icon: "" },
  7336: { condition: "Hemorrhoids", dbq: "Unknown", icon: "" },
  7337: { condition: "Pruritus ani", dbq: "Unknown", icon: "" },
  7338: { condition: "Inguinal", dbq: "Unknown", icon: "" },
  7339: { condition: "Ventral", dbq: "Unknown", icon: "" },
  7340: { condition: "Femoral", dbq: "Unknown", icon: "" },
  7342: { condition: "Visceroptosis", dbq: "Unknown", icon: "" },
  7343: { condition: "Digestive system", dbq: "Unknown", icon: "" },
  7344: { condition: "Digestive system", dbq: "Unknown", icon: "" },
  7345: { condition: "Disease, chronic, without cirrhosis", dbq: "Unknown", icon: "" },
  7346: { condition: "Hiatal", dbq: "Esophageal Conditions", icon: "🍴" },
  7347: { condition: "Pancreatitis", dbq: "Unknown", icon: "" },
  7348: { condition: "Vagotomy", dbq: "Unknown", icon: "" },
  7351: { condition: "Transplant", dbq: "Unknown", icon: "" },
  7354: { condition: "Hepatitis C", dbq: "Unknown", icon: "" },
  7500: { condition: "Kidney", dbq: "Unknown", icon: "" },
  7501: { condition: "Kidney", dbq: "Unknown", icon: "" },
  7502: { condition: "Nephritis, chronic", dbq: "Unknown", icon: "" },
  7504: { condition: "Pyelonephritis, chronic", dbq: "Unknown", icon: "" },
  7505: { condition: "Kidney", dbq: "Unknown", icon: "" },
  7507: { condition: "Nephrosclerosis, arteriolar", dbq: "Unknown", icon: "" },
  7508: { condition: "Nephrolithiasis", dbq: "Unknown", icon: "" },
  7509: { condition: "Hydronephrosis", dbq: "Unknown", icon: "" },
  7510: { condition: "Ureterolithiasis", dbq: "Unknown", icon: "" },
  7511: { condition: "Ureter, stricture of", dbq: "Unknown", icon: "" },
  7512: { condition: "Cystitis, chronic", dbq: "Unknown", icon: "" },
  7515: { condition: "Calculus in", dbq: "Unknown", icon: "" },
  7516: { condition: "Fistula in", dbq: "Unknown", icon: "" },
  7517: { condition: "Bladder", dbq: "Unknown", icon: "" },
  7518: { condition: "Stricture", dbq: "Unknown", icon: "" },
  7519: { condition: "Fistula", dbq: "Unknown", icon: "" },
  7520: { condition: "Penis half or more", dbq: "Unknown", icon: "" },
  7521: { condition: "Penis glans", dbq: "Unknown", icon: "" },
  7522: { condition: "Deformity, with loss of erectile power", dbq: "Genitourinary Conditions", icon: "🚻" },
  7523: { condition: "Atrophy, complete", dbq: "Unknown", icon: "" },
  7524: { condition: "Testis", dbq: "Unknown", icon: "" },
  7525: { condition: "Epididymo-orchitis", dbq: "Unknown", icon: "" },
  7527: { condition: "Prostate gland", dbq: "Unknown", icon: "" },
  7528: { condition: "Genitourinary", dbq: "Unknown", icon: "" },
  7529: { condition: "Genitourinary", dbq: "Unknown", icon: "" },
  7530: { condition: "Disease, chronic", dbq: "Unknown", icon: "" },
  7531: { condition: "Transplant", dbq: "Unknown", icon: "" },
  7532: { condition: "Tubular disorders", dbq: "Unknown", icon: "" },
  7533: { condition: "Cystic diseases", dbq: "Unknown", icon: "" },
  7534: { condition: "Atherosclerotic renal disease", dbq: "Unknown", icon: "" },
  7535: { condition: "Toxic nephropathy", dbq: "Unknown", icon: "" },
  7536: { condition: "Glomerulonephritis", dbq: "Unknown", icon: "" },
  7537: { condition: "Interstitial nephritis", dbq: "Unknown", icon: "" },
  7538: { condition: "Papillary necrosis", dbq: "Unknown", icon: "" },
  7539: { condition: "Amyloid disease", dbq: "Unknown", icon: "" },
  7540: { condition: "Disseminated intravascular coagulation", dbq: "Unknown", icon: "" },
  7541: { condition: "Involvement in systemic diseases", dbq: "Unknown", icon: "" },
  7542: { condition: "Neurogenic", dbq: "Unknown", icon: "" },
  7610: { condition: "Vulva disease or injury of", dbq: "Unknown", icon: "" },
  7611: { condition: "Vagina, disease or injury", dbq: "Unknown", icon: "" },
  7612: { condition: "Cervix disease or injury", dbq: "Unknown", icon: "" },
  7613: { condition: "Disease or injury", dbq: "Unknown", icon: "" },
  7614: { condition: "Fallopian tube", dbq: "Unknown", icon: "" },
  7615: { condition: "Disease or injury", dbq: "Unknown", icon: "" },
  7617: { condition: "Uterus and both ovaries", dbq: "Unknown", icon: "" },
  7618: { condition: "Uterus", dbq: "Unknown", icon: "" },
  7619: { condition: "Ovary", dbq: "Unknown", icon: "" },
  7620: { condition: "Ovaries, atrophy of both", dbq: "Unknown", icon: "" },
  7621: { condition: "Prolapse", dbq: "Unknown", icon: "" },
  7622: { condition: "Displacement", dbq: "Unknown", icon: "" },
  7623: { condition: "Pregnancy, surgical complications", dbq: "Unknown", icon: "" },
  7624: { condition: "Rectovaginal", dbq: "Unknown", icon: "" },
  7625: { condition: "Urethrovaginal", dbq: "Unknown", icon: "" },
  7626: { condition: "Breast surgery", dbq: "Unknown", icon: "" },
  7627: { condition: "Gynecological or breast", dbq: "Unknown", icon: "" },
  7628: { condition: "Gynecological or breast", dbq: "Unknown", icon: "" },
  7629: { condition: "Endometriosis", dbq: "Unknown", icon: "" },
  7700: { condition: "Anemia", dbq: "Unknown", icon: "" },
  7702: { condition: "Agranulocytosis", dbq: "Unknown", icon: "" },
  7703: { condition: "Leukemia", dbq: "Unknown", icon: "" },
  7704: { condition: "Polycythemia vera", dbq: "Unknown", icon: "" },
  7705: { condition: "Thrombocytopenia", dbq: "Unknown", icon: "" },
  7706: { condition: "Splenectomy", dbq: "Unknown", icon: "" },
  7707: { condition: "Spleen, injury of, healed", dbq: "Unknown", icon: "" },
  7709: { condition: "Hodgkin's", dbq: "Unknown", icon: "" },
  7710: { condition: "Adenitis", dbq: "Unknown", icon: "" },
  7715: { condition: "Non-Hodgkin's lymphoma", dbq: "Unknown", icon: "" },
  7716: { condition: "Aplastic anemia", dbq: "Unknown", icon: "" },
  7800: { condition: "Disfigurement of, head, face or neck", dbq: "Unknown", icon: "" },
  7801: { condition: "Burn scar(s) or scars(s) due to other causes, not of the head, face, or neck,", dbq: "Unknown", icon: "" },
  7802: { condition: "Burn scar(s) or scars(s) due to other causes, not of the head, face, or neck,", dbq: "Unknown", icon: "" },
  7804: { condition: "Unstable or painful", dbq: "Skin Conditions", icon: "🩹" },
  7805: { condition: "Other", dbq: "Unknown", icon: "" },
  7806: { condition: "Dermatitis or eczema", dbq: "Skin Conditions", icon: "🩹" },
  7807: { condition: "American (New World)", dbq: "Unknown", icon: "" },
  7808: { condition: "Old World", dbq: "Unknown", icon: "" },
  7809: { condition: "Erythematosus, discoid", dbq: "Unknown", icon: "" },
  7811: { condition: "Luposa (lupus vulgaris)", dbq: "Unknown", icon: "" },
  7813: { condition: "Dermatophytosis", dbq: "Unknown", icon: "" },
  7815: { condition: "Bullous disorders", dbq: "Unknown", icon: "" },
  7816: { condition: "Psoriasis", dbq: "Skin Conditions", icon: "🩹" },
  7817: { condition: "Exfoliative dermatitis", dbq: "Unknown", icon: "" },
  7818: { condition: "Skin", dbq: "Unknown", icon: "" },
  7819: { condition: "Skin", dbq: "Unknown", icon: "" },
  7820: { condition: "Infections of the skin", dbq: "Unknown", icon: "" },
  7821: { condition: "Cutaneous manifestations of collagen-vascular diseases", dbq: "Unknown", icon: "" },
  7822: { condition: "Papulosquamous disorders", dbq: "Unknown", icon: "" },
  7823: { condition: "Vitiligo", dbq: "Unknown", icon: "" },
  7824: { condition: "Keratinization, diseases of", dbq: "Unknown", icon: "" },
  7825: { condition: "Urticaria", dbq: "Unknown", icon: "" },
  7826: { condition: "Vasculitis, primary cutaneous", dbq: "Unknown", icon: "" },
  7827: { condition: "Erythema multiforme", dbq: "Unknown", icon: "" },
  7828: { condition: "Acne", dbq: "Unknown", icon: "" },
  7829: { condition: "Chloracne", dbq: "Unknown", icon: "" },
  7830: { condition: "Scarring alopecia", dbq: "Unknown", icon: "" },
  7831: { condition: "Alopecia areata", dbq: "Unknown", icon: "" },
  7832: { condition: "Hyperhidrosis", dbq: "Unknown", icon: "" },
  7833: { condition: "Malignant melanoma", dbq: "Unknown", icon: "" },
  7900: { condition: "Hyperthyroidism", dbq: "Unknown", icon: "" },
  7901: { condition: "Toxic adenoma", dbq: "Unknown", icon: "" },
  7902: { condition: "Nontoxic adenoma", dbq: "Unknown", icon: "" },
  7903: { condition: "Hypothyroidism", dbq: "Endocrine Disorders", icon: "⚖️" },
  7904: { condition: "Hyperparathyroidism", dbq: "Unknown", icon: "" },
  7905: { condition: "Hypoparathyroidism", dbq: "Unknown", icon: "" },
  7907: { condition: "Cushing's", dbq: "Unknown", icon: "" },
  7908: { condition: "Acromegaly", dbq: "Unknown", icon: "" },
  7909: { condition: "Insipidus", dbq: "Unknown", icon: "" },
  7911: { condition: "Addison's", dbq: "Unknown", icon: "" },
  7912: { condition: "Pluriglandular syndrome", dbq: "Unknown", icon: "" },
  7913: { condition: "Mellitus", dbq: "Endocrine Disorders", icon: "⚖️" },
  7914: { condition: "Endocrine", dbq: "Unknown", icon: "" },
  7915: { condition: "Endocrine", dbq: "Unknown", icon: "" },
  7916: { condition: "Hyperpituitarism", dbq: "Unknown", icon: "" },
  7917: { condition: "Hyperaldosteronism", dbq: "Unknown", icon: "" },
  7918: { condition: "Pheochromocytoma", dbq: "Unknown", icon: "" },
  7919: { condition: "C-cell hyperplasia, thyroid", dbq: "Unknown", icon: "" },
  8000: { condition: "Encephalitis, epidemic, chronic", dbq: "Unknown", icon: "" },
  8002: { condition: "Brain", dbq: "Unknown", icon: "" },
  8003: { condition: "Brain", dbq: "Unknown", icon: "" },
  8004: { condition: "Agitans", dbq: "Unknown", icon: "" },
  8005: { condition: "Bulbar palsy", dbq: "Unknown", icon: "" },
  8007: { condition: "Embolism, brain", dbq: "Unknown", icon: "" },
  8008: { condition: "Thrombosis, brain", dbq: "Unknown", icon: "" },
  8009: { condition: "Brain", dbq: "Unknown", icon: "" },
  8010: { condition: "Myelitis", dbq: "Unknown", icon: "" },
  8011: { condition: "Poliomyelitis, anterior", dbq: "Unknown", icon: "" },
  8012: { condition: "Hematomyelia", dbq: "Unknown", icon: "" },
  8013: { condition: "Cerebrospinal", dbq: "Unknown", icon: "" },
  8014: { condition: "Meningovascular", dbq: "Unknown", icon: "" },
  8015: { condition: "Tabes dorsalis", dbq: "Unknown", icon: "" },
  8017: { condition: "Amyotrophic lateral sclerosis", dbq: "Unknown", icon: "" },
  8018: { condition: "Multiple sclerosis", dbq: "Unknown", icon: "" },
  8019: { condition: "Meningitis, cerebrospinal, epidemic", dbq: "Unknown", icon: "" },
  8020: { condition: "Brain", dbq: "Unknown", icon: "" },
  8021: { condition: "Spinal cord", dbq: "Unknown", icon: "" },
  8022: { condition: "Spinal cord", dbq: "Unknown", icon: "" },
  8023: { condition: "Progressive muscular atrophy", dbq: "Unknown", icon: "" },
  8024: { condition: "Syringomyelia", dbq: "Unknown", icon: "" },
  8025: { condition: "Myasthenia gravis", dbq: "Unknown", icon: "" },
  8045: { condition: "Traumatic brain injury residuals", dbq: "Unknown", icon: "" },
  8046: { condition: "Cerebral arteriosclerosis", dbq: "Unknown", icon: "" },
  8100: { condition: "Migraine", dbq: "Headaches", icon: "🤕" },
  8103: { condition: "Tic, convulsive", dbq: "Unknown", icon: "" },
  8104: { condition: "Paramyoclonus multiplex", dbq: "Unknown", icon: "" },
  8105: { condition: "Sydenham's", dbq: "Unknown", icon: "" },
  8106: { condition: "Huntington's", dbq: "Unknown", icon: "" },
  8107: { condition: "Athetosis", dbq: "Unknown", icon: "" },
  8108: { condition: "Narcolepsy", dbq: "Unknown", icon: "" },
  8205: { condition: "Fifth (trigeminal)", dbq: "Unknown", icon: "" },
  8207: { condition: "Seventh (facial)", dbq: "Unknown", icon: "" },
  8209: { condition: "Ninth (glossopharyngeal)", dbq: "Unknown", icon: "" },
  8210: { condition: "Tenth (pneumogastric, vagus)", dbq: "Unknown", icon: "" },
  8211: { condition: "Eleventh (spinal accessory, external branch)", dbq: "Unknown", icon: "" },
  8212: { condition: "Twelfth (hypoglossal)", dbq: "Unknown", icon: "" },
  8305: { condition: "Fifth (trigeminal)", dbq: "Unknown", icon: "" },
  8307: { condition: "Seventh (facial)", dbq: "Unknown", icon: "" },
  8309: { condition: "Ninth (glossopharyngeal)", dbq: "Unknown", icon: "" },
  8310: { condition: "Tenth (pneumogastric, vagus)", dbq: "Unknown", icon: "" },
  8311: { condition: "Eleventh (spinal accessory, external branch)", dbq: "Unknown", icon: "" },
  8312: { condition: "Twelfth (hypoglossal)", dbq: "Unknown", icon: "" },
  8405: { condition: "Fifth (trigeminal)", dbq: "Unknown", icon: "" },
  8407: { condition: "Seventh (facial)", dbq: "Unknown", icon: "" },
  8409: { condition: "Ninth (glossopharyngeal)", dbq: "Unknown", icon: "" },
  8410: { condition: "Tenth (pneumogastric, vagus)", dbq: "Unknown", icon: "" },
  8411: { condition: "Eleventh (spinal accessory, external branch)", dbq: "Unknown", icon: "" },
  8412: { condition: "Twelfth (hypoglossal)", dbq: "Unknown", icon: "" },
  8510: { condition: "Upper radicular group", dbq: "Unknown", icon: "" },
  8511: { condition: "Middle radicular group", dbq: "Unknown", icon: "" },
  8512: { condition: "Lower radicular group", dbq: "Unknown", icon: "" },
  8513: { condition: "All radicular groups", dbq: "Unknown", icon: "" },
  8514: { condition: "Musculospiral (radial)", dbq: "Unknown", icon: "" },
  8515: { condition: "Median", dbq: "Neuropathy", icon: "🦵" },
  8516: { condition: "Ulnar", dbq: "Unknown", icon: "" },
  8517: { condition: "Musculocutaneous", dbq: "Unknown", icon: "" },
  8518: { condition: "Circumflex", dbq: "Unknown", icon: "" },
  8519: { condition: "Long thoracic", dbq: "Unknown", icon: "" },
  8520: { condition: "Sciatic", dbq: "Neuropathy", icon: "🦵" },
  8521: { condition: "External popliteal (common peroneal)", dbq: "Unknown", icon: "" },
  8522: { condition: "Musculocutaneous (superficial peroneal)", dbq: "Unknown", icon: "" },
  8523: { condition: "Anterior tibial nerve (deep peroneal)", dbq: "Unknown", icon: "" },
  8524: { condition: "Internal popliteal (tibial)", dbq: "Unknown", icon: "" },
  8525: { condition: "Posterior tibial nerve", dbq: "Unknown", icon: "" },
  8526: { condition: "Anterior crural nerve (femoral)", dbq: "Unknown", icon: "" },
  8527: { condition: "Internal saphenous", dbq: "Unknown", icon: "" },
  8528: { condition: "Obturator", dbq: "Unknown", icon: "" },
  8529: { condition: "External cutaneous nerve of thigh", dbq: "Unknown", icon: "" },
  8530: { condition: "Ilio-inguinal", dbq: "Unknown", icon: "" },
  8540: { condition: "Neurogenic origin", dbq: "Unknown", icon: "" },
  8610: { condition: "Upper radicular group", dbq: "Unknown", icon: "" },
  8611: { condition: "Middle radicular group", dbq: "Unknown", icon: "" },
  8612: { condition: "Lower radicular group", dbq: "Unknown", icon: "" },
  8613: { condition: "All radicular groups", dbq: "Unknown", icon: "" },
  8614: { condition: "Musculospiral (radial)", dbq: "Unknown", icon: "" },
  8615: { condition: "Median", dbq: "Unknown", icon: "" },
  8616: { condition: "Ulnar", dbq: "Unknown", icon: "" },
  8617: { condition: "Musculocutaneous", dbq: "Unknown", icon: "" },
  8618: { condition: "Circumflex", dbq: "Unknown", icon: "" },
  8619: { condition: "Long thoracic", dbq: "Unknown", icon: "" },
  8620: { condition: "Sciatic", dbq: "Neuropathy", icon: "🦵" },
  8621: { condition: "External popliteal (common peroneal)", dbq: "Unknown", icon: "" },
  8622: { condition: "Musculocutaneous (superficial peroneal)", dbq: "Unknown", icon: "" },
  8623: { condition: "Anterior tibial (deep peroneal)", dbq: "Unknown", icon: "" },
  8624: { condition: "Internal popliteal (tibial)", dbq: "Unknown", icon: "" },
  8625: { condition: "Posterior tibial", dbq: "Unknown", icon: "" },
  8626: { condition: "Anterior crural (femoral)", dbq: "Unknown", icon: "" },
  8627: { condition: "Internal saphenous", dbq: "Unknown", icon: "" },
  8628: { condition: "Obturator", dbq: "Unknown", icon: "" },
  8629: { condition: "External cutaneous nerve of thigh", dbq: "Unknown", icon: "" },
  8630: { condition: "Ilio-inguinal", dbq: "Unknown", icon: "" },
  8710: { condition: "Upper radicular group", dbq: "Unknown", icon: "" },
  8711: { condition: "Middle radicular group", dbq: "Unknown", icon: "" },
  8712: { condition: "Lower radicular group", dbq: "Unknown", icon: "" },
  8713: { condition: "All radicular groups", dbq: "Unknown", icon: "" },
  8714: { condition: "Musculospiral (radial)", dbq: "Unknown", icon: "" },
  8715: { condition: "Median", dbq: "Unknown", icon: "" },
  8716: { condition: "Ulnar", dbq: "Unknown", icon: "" },
  8717: { condition: "Musculocutaneous", dbq: "Unknown", icon: "" },
  8718: { condition: "Circumflex", dbq: "Unknown", icon: "" },
  8719: { condition: "Long thoracic", dbq: "Unknown", icon: "" },
  8720: { condition: "Sciatic", dbq: "Unknown", icon: "" },
  8721: { condition: "External popliteal (common peroneal)", dbq: "Unknown", icon: "" },
  8722: { condition: "Musculocutaneous (superficial peroneal)", dbq: "Unknown", icon: "" },
  8723: { condition: "Anterior tibial (deep peroneal)", dbq: "Unknown", icon: "" },
  8724: { condition: "Internal popliteal (tibial)", dbq: "Unknown", icon: "" },
  8725: { condition: "Posterior tibial", dbq: "Unknown", icon: "" },
  8726: { condition: "Anterior crural (femoral)", dbq: "Unknown", icon: "" },
  8727: { condition: "Internal saphenous", dbq: "Unknown", icon: "" },
  8728: { condition: "Obturator", dbq: "Unknown", icon: "" },
  8729: { condition: "External cutaneous nerve of thigh", dbq: "Unknown", icon: "" },
  8730: { condition: "Ilio-inguinal", dbq: "Unknown", icon: "" },
  8910: { condition: "Grand mal", dbq: "Unknown", icon: "" },
  8911: { condition: "Petit mal", dbq: "Unknown", icon: "" },
  8912: { condition: "Jacksonian and focal motor or sensory", dbq: "Unknown", icon: "" },
  8913: { condition: "Diencephalic", dbq: "Unknown", icon: "" },
  8914: { condition: "Psychomotor", dbq: "Unknown", icon: "" },
  9201: { condition: "Disorganized type", dbq: "Unknown", icon: "" },
  9202: { condition: "Catatonic type", dbq: "Unknown", icon: "" },
  9203: { condition: "Paranoid type", dbq: "Unknown", icon: "" },
  9204: { condition: "Undifferentiated type", dbq: "Unknown", icon: "" },
  9205: { condition: "Residual type", dbq: "Unknown", icon: "" },
  9208: { condition: "Delusional disorder", dbq: "Unknown", icon: "" },
  9210: { condition: "Psychotic disorder", dbq: "Unknown", icon: "" },
  9211: { condition: "Schizoaffective disorder", dbq: "Unknown", icon: "" },
  9300: { condition: "Delirium", dbq: "Unknown", icon: "" },
  9301: { condition: "Infection", dbq: "Unknown", icon: "" },
  9304: { condition: "Head trauma", dbq: "Unknown", icon: "" },
  9305: { condition: "Vascular dementia", dbq: "Unknown", icon: "" },
  9310: { condition: "Unknown etiology", dbq: "Unknown", icon: "" },
  9312: { condition: "Alzheimers", dbq: "Unknown", icon: "" },
  9326: { condition: "Other medical conditions", dbq: "Unknown", icon: "" },
  9327: { condition: "Organic mental disorder", dbq: "Unknown", icon: "" },
  9400: { condition: "Generalized anxiety disorder", dbq: "Mental Disorders", icon: "💬" },
  9403: { condition: "Specific (simple) phobia", dbq: "Unknown", icon: "" },
  9404: { condition: "Obsessive compulsive disorder", dbq: "Unknown", icon: "" },
  9410: { condition: "Other and unspecified neurosis", dbq: "Unknown", icon: "" },
  9411: { condition: "Posttraumatic stress disorder", dbq: "PTSD", icon: "🧠" },
  9412: { condition: "Panic disorder", dbq: "Unknown", icon: "" },
  9413: { condition: "Not otherwise specified", dbq: "Unknown", icon: "" },
  9416: { condition: "Amnesia, fugue, identity disorders", dbq: "Unknown", icon: "" },
  9417: { condition: "Depersonalization disorder", dbq: "Unknown", icon: "" },
  9421: { condition: "Somatization disorder", dbq: "Mental Disorders", icon: "💬" },
  9422: { condition: "Pain disorder", dbq: "Unknown", icon: "" },
  9423: { condition: "Undifferentiated somatoform disorder", dbq: "Unknown", icon: "" },
  9424: { condition: "Conversion disorder", dbq: "Unknown", icon: "" },
  9425: { condition: "Hypochondriasis", dbq: "Unknown", icon: "" },
  9431: { condition: "Cyclothymic disorder", dbq: "Unknown", icon: "" },
  9432: { condition: "Bipolar disorder", dbq: "Mental Disorders", icon: "💬" },
  9433: { condition: "Dysthymic disorder", dbq: "Unknown", icon: "" },
  9434: { condition: "Major depressive disorder", dbq: "Unknown", icon: "" },
  9435: { condition: "Mood disorder not otherwise specified", dbq: "Unknown", icon: "" },
  9440: { condition: "Chronic adjustment disorder", dbq: "Mental Disorders", icon: "💬" },
  9520: { condition: "Anorexia nervosa", dbq: "Unknown", icon: "" },
  9521: { condition: "Bulimia nervosa", dbq: "Unknown", icon: "" },
  9900: { condition: "Osteomyelitis maxilla or mandible", dbq: "Unknown", icon: "" },
  9901: { condition: "Complete", dbq: "Unknown", icon: "" },
  9902: { condition: "One-half", dbq: "Unknown", icon: "" },
  9903: { condition: "Mandible", dbq: "Unknown", icon: "" },
  9904: { condition: "Mandible", dbq: "Unknown", icon: "" },
  9905: { condition: "Temporomandibular articulation", dbq: "Unknown", icon: "" },
  9906: { condition: "Whole or part", dbq: "Unknown", icon: "" },
  9907: { condition: "Less than one-half", dbq: "Unknown", icon: "" },
  9908: { condition: "Condyloid process", dbq: "Unknown", icon: "" },
  9909: { condition: "Coronoid process", dbq: "Unknown", icon: "" },
  9911: { condition: "Half or more", dbq: "Unknown", icon: "" },
  9912: { condition: "Less than half", dbq: "Unknown", icon: "" },
  9913: { condition: "Teeth, loss of", dbq: "Unknown", icon: "" },
  9914: { condition: "More than half", dbq: "Unknown", icon: "" },
  9915: { condition: "Less than half", dbq: "Unknown", icon: "" },
  9916: { condition: "Maxilla, malunion or nonunion", dbq: "Unknown", icon: "" },
};
;

// DBQ form links
const formLinks = {
  "Audiology and Tinnitus": "https://www.benefits.va.gov/compensation/docs/Ear_Including_Vestibular_and_Infectious.pdf",
  "Hearing Loss":                null,
  "PTSD":                        "https://www.benefits.va.gov/compensation/docs/PTSD_Review.pdf",
  "Mental Disorders":            "https://www.benefits.va.gov/compensation/docs/Mental_Disorders.pdf",
  "Lumbosacral and Thoracic Spine Conditions": "https://www.benefits.va.gov/compensation/docs/Back_Thoracolumbar_Spine.pdf",
  "Cervical Spine (Neck) Conditions":          "https://www.benefits.va.gov/compensation/docs/Neck_Conditions_Cervical_Spine.pdf",
  "Neuropathy":                  "https://www.benefits.va.gov/compensation/docs/Peripheral_Nerves.pdf",
  "Headaches":                   "https://www.benefits.va.gov/compensation/docs/Headaches_Including_Migraines.pdf",
  "Knee and Lower Leg Conditions":"https://www.benefits.va.gov/compensation/docs/Knee_and_Lower_Leg.pdf",
  "Foot Conditions":             "https://www.benefits.va.gov/compensation/docs/Foot_Conditions_Including_Flatfoot_Pes_Planus.pdf",
  "Joint Conditions":            "https://www.benefits.va.gov/compensation/docs/Bones_and_Other_Skeletal_Conditions.pdf",
  "Hypertension":                "https://www.benefits.va.gov/compensation/docs/hypertension.pdf",
  "Coronary Artery Disease":     "https://www.benefits.va.gov/compensation/docs/Heart.pdf",
  "Respiratory Conditions":      "https://www.benefits.va.gov/compensation/docs/Respiratory_Conditions_Other_than_Tuberculosis_and_Sleep_Apnea.pdf",
  "Nasal and Sinus Conditions":  "https://www.benefits.va.gov/compensation/docs/Sinusitis_Rhinitis_and_Other_Conditions_of_the_Nose_Throat_Larynx_and_Pharynx.pdf",
  "Sleep Apnea":                 "https://www.benefits.va.gov/compensation/docs/Sleep_Apnea.pdf",
  "Esophageal Conditions":       "https://www.benefits.va.gov/compensation/docs/esophageal-disorders.pdf",
  "Genitourinary Conditions":    "https://www.benefits.va.gov/compensation/docs/Urinary_Tract_Conditions.pdf",
  "Skin Conditions":             "https://www.benefits.va.gov/compensation/docs/Skin_Diseases.pdf",
  "Endocrine Disorders":         "https://www.benefits.va.gov/compensation/docs/Diabetes_Mellitus.pdf"
};

// Icons mapping for visual cues
const iconMap = {
  headache: "🧠", migraine: "🧠", back: "🦴", spine: "🦴",
  neck: "🦴", knee: "🦵", leg: "🦵", foot: "🦶",
  ankle: "🦶", mental: "🧘", depression: "🧘",
  anxiety: "🧘", ptsd: "🧘", nerve: "🔌",
  neuropathy: "🔌", radiculopathy: "🔌", heart: "❤️",
  hypertension: "❤️", sinus: "👃", gerd: "🔥",
  reflux: "🔥", skin: "🩹", dermatitis: "🩹",
  eczema: "🩹", diabetes: "🍬", endocrine: "🍬",
  sleep: "😴"
};
